config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: 'homes#top'

  get "home/about" => "homes#about"

  get "/books" => "books#index"


  post "/books/:id" => "books#create"

  post "/users" => "books#create"

  post "/users/:id" => "books#create"

  delete "/books/:id" => "books#destroy", as: "destroy_book"

  resources :users, only: [:index, :show, :edit, :update]

  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 1, maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, uniqueness: true
  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

   def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

   def after_sign_in_path_for(resource)
    user_path(current_user.id)
   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all
  end

  def create
   @book=Book.new(book_params)
   @book.user_id=current_user.id
   if @book.save
     flash[:notice]="You have created book successfully."
     redirect_to book_path(@book.id)
   else
     @books=Book.all
     render :index
   end
  end

  def show
    @bookfind=Book.find(params[:id])
    @book=Book.new
    user_id=@bookfind.user_id
    @user=User.find(user_id)
    @book=Book.new
  end

  def edit
    @book=Book.find(params[:id])
    user_id=@book.user_id
    login_user_id=current_user.id
    if(user_id != login_user_id)
      redirect_to books_path
    end 
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

 private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
    @book=Book.new
    @user=current_user
  end

  def create
    @book=Book.new(book_params)
    if @book.save
     redirect_to book_path(@book.id)
    else
     render :index
   end
  end

  def show
    @user=User.find(params[:id])
    @books=Book.all
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
    user_id=params[:id].to_i
    login_user_id=current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(login_user_id)
    end 
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto col-md-8">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %> error prohibited this obj from being saved:
        </h3>
         <ul>
   　　　　　<% @book.errors.full_messages.each do |message| %>
     　　　　　 <li><%= message %></li>
          <% end %>
         </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <h6>Title</h6>
        <%= f.text_field :title, size: "57" %>
      </div>
      <div class="form-group">
        <h6>Opinion</h6>
        <%= f.text_area :body, size: "60" %>
      </div>

      <button type="submit" class="btn btn-success btn-md mt-3">Update Book</button>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
 <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container  px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td><strong><%= current_user.name %></strong></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><strong><%= current_user.introduction %></strong></td>
          </tr>
        </tbody>
      </table>

      <%= link_to edit_user_path(current_user.id) do %>
        <button class="btn btn-outline-secondary btn-block btn-lg">
         <i class="fas fa-user-cog"></i>
        </button>
      <% end %>

       <h2 class="mt-3">New book</h2>
       <%= form_with model: @book do |f| %>

       <h5 class="font-weight-light">Title</h5>
       <%= f.text_field :title %>

       <h5 class="font-weight-light">Opinion</h5>
       <%= f.text_area :body %>

       <button type="submit" class="btn btn-success btn-md mt-3">Create Book</button>

       <% end %>
    </div>

<%# ここからページ右側 %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover">
        <thead>
         <tr>
           <th></th>
           <th scope="col"><strong>Title</strong></th>
           <th scope="col"><strong>Opinion</strong></th>
         </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
           <tr>
            <td><%= link_to user_path(book.user_id) do %>
             <%= image_tag book.user.get_profile_image(80,80) %>
             <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td><strong><%= @user.name %></strong></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><strong><%= @user.introduction %></strong></td>
          </tr>
        </tbody>
      </table>

       <%= link_to edit_user_path(@user.id) do %>
        <button class="btn btn-outline-secondary btn-block btn-lg">
         <i class="fas fa-user-cog"></i>
        </button>
       <% end %>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>

       <h5 class="font-weight-light">Title</h5>
        <%= f.text_field :title %>

       <h5 class="font-weight-light">Opinion</h5>
        <%= f.text_area :body %>

       <button type="submit" class="btn btn-success btn-md mt-3">Create Book</button>

      <% end %>
    </div>

    <%#ここからページ右側 %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th>
            <td>
                <%= image_tag @user.get_profile_image(80,80) %>
                <%= link_to user_path(@user.id) do %>
                 <h6><%= @user.name %></h6>
                <% end %>
            </td>
            <td><%= link_to book_path(@bookfind.id) do %>
                 <%= @bookfind.title %>
                <% end %>
            </td>
            <td><%= @bookfind.body %></td>

            <% if(current_user.id==@bookfind.user_id) %>
            <td>
              <%= link_to edit_book_path(@bookfind.id) do %>
              <button class= "btn btn-success btn-sm">Edit</button>
              <% end %>
            </td>
            <td><%= link_to destroy_book_path(@bookfind.id), method: :delete, "data-confirm" => "本当に排除しますか？" do %>
                <button class= "btn btn-danger btn-sm">Destroy</button>
                <% end %>
            </td>
            <% end %>
            </th>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <script src="https://kit.fontawesome.com/822b72a28c.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="mx-auto mt-3">
       <h1>
         welcome to <i class="fas fa-book"></i><strong>Bookers!</strong>
       </h1>
      </div>
    </div>
  </body>

app/views/homes/top.html.erb
 <div class="container">
     <div class="row">
      <div class="mx-auto mt-3 col-11 col-sm-10 col-md-9 col-lg-7 col-xl-6">
       <h1>
         welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong>
       </h1>

       <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

       <p>you can share and exchange your opinions,inpressions,and emotions</p>

       <p>about various books!</p>
      </div>
     </div>
   </div>
   <div class="container mx-auto">
     <div class="row">
       <div class="mx-auto col-11 col-sm-10 col-md-9 col-lg-7 col-xl-6">
         <div class="btn-wrapper col-10 mx-auto mt-1">
          <div class="row">
           <!--<a class="btn btn-info btn-sm btn-block mb-4 sign_in" href="/users/sign_in">-->
          　 <!--Log in-->
           <!--</a>-->
           <%= link_to "Log in", "/users/sign_in",  class:"btn btn-info btn-sm btn-block mb-4 sign_in" %>
          </div>
          <div class="row">
           <!--<a class="bt-->
            <!--Sign up-->
           <!--</a>-->
           <%= link_to "Sign up", "/users/sign_up",  class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
         </div>
       </div>
     </div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers2</title>
    <script src="https://kit.fontawesome.com/822b72a28c.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container">
    <a class="navbar-brand" href="/"><h4>Bookers</h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" area-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
          <i class="fas fa-home"></i>
          Home
          <% end %>
         </li>
         <li>
          <%= link_to "/users", class: "nav-link text-light" do %>
          <i class="fas fa-users"></i>
          Users
          <% end %>
         </li>
         <li>
          <%= link_to "/books", class: "nav-link text-light" do %>
          <i class="fas fa-book-open"></i>
          Books
          <% end %>
         </li>
         <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
          <i class="fas fa-sign-out-alt"></i>
          Log out
          <% end %>
         </li>
        <% else %>
         <li class="nav-item">
          <%= link_to root_path, class: "nav-link text-light" do %>
           <i class="fas fa-home"></i>
          Home
          <% end %>
         </li>
         <li class="nav-item">
          <%= link_to home_about_path, class: "nav-link text-light" do %>
          <i class="fas fa-link"></i>
          About
          <% end %>
         <li>
          <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
          <i class="fas fa-user-plus"></i>
          Sign up
          <% end %>
         </li>
         <li>
          <%= link_to new_user_session_path, class: "nav-link text-light" do %>
          <i class="fas fa-sign-in-alt"></i>
          Log in
          <% end %>
         </li>
        <% end %>
      </ul>
    </div>
   </div>
  </nav>
  </header>
  <%= flash[:notice] %>
  <%= yield %>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <h5>CopyRight Infratop.inc</h5>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto col-md-8">
      <h2>User info</h2>
      <% if @user.errors.any? %>
       <h3>
        <%= @user.errors.count %> error prohibited this obj from being saved:
       </h3>
       <ul>
        <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <h6>Name</h6>
        <%= f.text_field :name, size: "57" %>
      </div>
      <div class="form-group">
        <h6>image</h6>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class="form-group">
        <h6>Introduction</h6>
        <%= f.text_area :introduction, size: "60" %>
      </div>

      <button type="submit" class="btn btn-secondary btn-md mt-3">Update User</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>

      <table class="table">
        <tbody>
          <tr>
           <%= image_tag current_user.get_profile_image(100,100) %>
          </tr>
          <tr>
            <th scope="row">name</th>
            <td scope="col"><strong><%= current_user.name %></strong></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><strong><%= current_user.introduction %></strong></td>
          </tr>
        </tbody>
      </table>

      <%= link_to edit_user_path(current_user.id) do %>
        <button class="btn btn-outline-secondary btn-block btn-lg">
         <i class="fas fa-user-cog"></i>
        </button>
      <% end %>

       <h2 class="mt-3">New book</h2>
       <%= form_with model: @book do |f| %>

       <h5 class="font-weight-light">Title</h5>
       <%= f.text_field :title %>

       <h5 class="font-weight-light">Opinion</h5>
       <%= f.text_area :body %>

       <button type="submit" class="btn btn-success btn-md mt-3">Create Book</button>

       <% end %>
    </div>

  <%#ここからページ右側 %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th scope="col"><strong>image</strong></th>
            <th scope="col"><strong>name</strong></th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
         <tr>
          <td>
               <%= image_tag user.get_profile_image(80,80) %>
          </td>
          <td>
              <%= user.name %>
          </td>
          <td>
              <%= link_to user_path(user.id) do %>
               <p>Show</p>
              <% end %>
          </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td><strong><%= @user.name %></strong></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><strong><%= @user.introduction %></strong></td>
          </tr>
        </tbody>
      </table>

       <%= link_to edit_user_path(@user.id) do %>
        <button class="btn btn-outline-secondary btn-block btn-lg">
         <i class="fas fa-user-cog"></i>
        </button>
       <% end %>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>

       <h5 class="font-weight-light">Title</h5>
        <%= f.text_field :title %>

       <h5 class="font-weight-light">Opinion</h5>
        <%= f.text_area :body %>

       <button type="submit" class="btn btn-success btn-md mt-3">Create Book</button>

      <% end %>
    </div>

  <%#ここからページ右側%>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>

     <table class="table table-hover">
       <thead>
         <tr>
           <th scope="col"></th>
           <th scope="col">Title</th>
           <th scope="col">Opinion</th>
         </tr>
       </thead>
       <tbody>
         <% @books.each do |book| %>
         <% if(@user.id==book.user_id) %>
         <tr>
           <td><%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
           </td>
           <td>
          　<%= link_to book_path(book.id) do %>
          　 <%= book.title %>
            <% end %>
           </td>
           <td>
             <%= book.body %>
           </td>
         </tr>
         <% end %>
         <% end %>
       </tbody>
     </table>
   </div>
  </div>
</div>